### ISSUE TITLE
Clarifying dependencies for the plugin in the readme

### ISSUE THREAD

**Issue by ahmadalfy** [jonathantneal/postcss-logical#2]
According to [this demo](https://jonathantneal.github.io/postcss-logical-properties/) when I try:

```css
.test {
  float: inline-start;
}
```

The output should be:
```css
[dir="ltr"] .test {
    float: left
}
[dir="rtl"] .test {
    float: right
}
```

I get different output in my workflow:

```css
.test:dir(ltr) {
  float: left;
}

.test:dir(rtl) {
  float: right;
}
```

I thought the problem might be due to my browserlist and the configuration for `css-next`. I did a little research and found the [postcss-dir-pseudo-class](https://github.com/jonathantneal/postcss-dir-pseudo-class) plugin. Adding it to my flow transformed the output to:

```css
.test {
  [dir="ltr"] & {
  float: left;
  }
  [dir="rtl"] & {
  float: right;
  }
}
```

I figured that I will need another plugin to transform this into something the browsers can understand; [postcss-nested](https://github.com/postcss/postcss-nested).

The question is, shouldn't we clarify the requirements for the plugin? I think it will save time and hassle. I spent at least 30 minutes trying to figure all this out.
