### ISSUE TITLE
Rendered CSS is wrong. It is '.class:dir(ltr)' instead of '[dir="ltr"] .class'

### ISSUE THREAD

**Issue by basher** [jonathantneal/postcss-logical#23]
According to [this bug](https://github.com/csstools/postcss-logical/issues/2) the issue should have been resolved.

`.postcssrc`:
```
{
  "plugins": {
    "autoprefixer": true,
    "postcss-logical": {
      "preserve": "true",
    }
  }
}
```

HTML, with `dir` attribute specified.
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>...</head>
<body>
  <div class="widget">
    <div class="widget-sidebar">...</div>
    <div class="widget-content">...</div>
  </div>
...
```

SCSS:
```scss
.widget {
  &-sidebar {
    margin-inline-end: 2rem;
  }
}
```

Rendered CSS:
```css
.widget-sidebar:dir(ltr){margin-right:2rem}.widget-sidebar:dir(rtl){margin-left:2rem}.widget-sidebar{margin-inline-end:2rem}
```

Btw, I'm using Parcel to bundle my UI assets, not Webpack or Gulp.

**Comment by ahmadalfy** [comment]
You can add [this plugin](https://github.com/jonathantneal/postcss-dir-pseudo-class) and it will resolve your issue.

My workflow with the working configuration:
https://github.com/ahmadalfy/workflow/blob/master/postcss.config.js#L5-L6

**Comment by basher** [comment]
Thanks @ahmadalfy - works a treat.

Rendered CSS:
```css
[dir=ltr] .widget-sidebar{margin-right:3rem}[dir=rtl] .widget-sidebar{margin-left:3rem}.widget-sidebar{margin-inline-end:3rem}
```

`.postcssrc`:
```
{
  "plugins": {
    "autoprefixer": true,
    "postcss-logical": {
      "preserve": "true",
    },
    "postcss-dir-pseudo-class": {}
  }
}
```

I think it would be useful to mention the additonal plugin in the `postcss-logical README`.
