### ISSUE TITLE
Transform origin is missing

### ISSUE THREAD

**Issue by ahmadalfy** [jonathantneal/postcss-logical#24]
I was expecting `transform-origin` to work as expected.

```css
.selector {
  transform-origin: inline-end;
}

[dir="ltr"] .selector {
  transform-origin: right;
}

[dir="rtl"] .selector {
  transform-origin: left;
}
```

I will be happy to submit a PR
