### ISSUE TITLE
`border-block-start-width` & `border-block-end-width` not transformed

### ISSUE THREAD

**Issue by yaaax** [jonathantneal/postcss-logical#27]
Hi there,

It looks like `border-block-start-width` and `border-block-end-width` are not transformed.
In a _top to bottom_ block flow:
`border-block-start-width`  should become  `border-top-width`
`border-block-end-width`  should become  `border-bottom-width`

See: https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-width

Probably something to add here ?
https://github.com/csstools/postcss-logical/blob/master/src/lib/transform-border.js

btw, this plugin is a really nice initiative, thanks ;) (I wish I could find time to help more!)

**Comment by querkmachine** [comment]
This is also an issue with `border-block-start-color` and `border-block-end-color`, though in that case it's transforming them directly into `border-top` and `border-bottom` rather than the more specific `border-top-color` and `border-bottom-color`.

**Comment by romainmenke** [comment]
This should be fixed

**Comment by hirasso** [comment]
Hi there, thank you for this great project! I have the same issue. Some properties like e.g. `border-end-end-radius` are not being converted. They are just erased. I'm using V. `5.0.0`

**Comment by romainmenke** [comment]
@hirasso Can you provide css snippets with expected behaviour for before and after so that we can add a test and then a fix?

**Comment by hirasso** [comment]
@romainmenke sure, thanks for the quick response!

Actually, looking at the generated `css`, I realized that the values _do_ get converted. They just don't seem to have any effect, since `:dir(ltr)` is not supported in my dev browser (`chrome95`). It really looks like this pseudo selector has [very poor browser support](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir#browser_compatibility). Did I miss something? 

Before:
```scss
button {
  display: inline-block;
  margin-inline: 20px;
  margin-inline-start: 10px;
  border-end-end-radius: 10px;
}
```
After:
```css
button:dir(ltr) {
  margin-left: 10px;
}

button:dir(rtl) {
  margin-right: 10px;
}

button:dir(ltr) {
  border-bottom-right-radius: 10px;
}

button:dir(rtl) {
  border-bottom-left-radius: 10px;
}

button {
  display: inline-block;
  margin-left: 20px;
  margin-right: 20px;
}
```

...I can confirm, it's working in Firefox...
