### ISSUE TITLE
Add using non shorthand CSS properties

### ISSUE THREAD

**Issue by max-norin** [jonathantneal/postcss-logical#29]
According to the [caniuse](https://caniuse.com/#search=padding-inline) not all browsers support shorthand CSS properties such as `padding-inline` `padding-block` and etc. 
There is suggestion to add a new option to the plugin for deploying shorthand CSS properties.
```pcss
.banner {
  padding-inline: 20px 40px;
}

/* becomes */

.banner {
  padding-inline-start: 20px;
  padding-inline-end: 40px;
  padding-inline: 20px 40px;
}
```

**Comment by ahmadalfy** [comment]
This actually translates to

```css
.banner:dir(ltr) {
  padding-left: 20px;
  padding-right: 40px;
}

.banner:dir(rtl) {
  padding-right: 20px;
  padding-left: 40px;
}
```

and with the help of another plugin [PostCSS dir pseudo class](https://github.com/jonathantneal/postcss-dir-pseudo-class) it translates to non-logical properties that work in the browsers
