### ISSUE TITLE
Is logical keyword generating correct output?

### ISSUE THREAD

**Issue by bakura10** [jonathantneal/postcss-logical#32]
Hi,

I have a doubt about how the library generate code when using the "logical" keyword. For instance the following code:

```css
ul {
  margin: logical 28px 0 28px 1.25em;
}
```

Generate this:

```css
[dir="ltr"] ul {
  margin: 28px 1.25em 28px 0;
}

[dir="rtl"] ul {
  margin: 28px 0 28px 1.25em;
}
```

Is this the expected output as per specification? Should not the logical follow by default the "LTR" (most common) variation? Intuitively I would have expected the opposite output, as this means that I should actually transform first the various direction before using the logical keyword?
