### ISSUE TITLE
logical properties aren't translated inside transition

### ISSUE THREAD

**Issue by ahmadalfy** [jonathantneal/postcss-logical#4]
As the title says, I guess this:

```css
.element {
    transition: 1s inset-inline-start ease;
}
```
should be translated to:

```css
.element:dir(ltr) {
    transition: 1s left ease;
}

.element:dir(rtl) {
    transition: 1s right ease;
}
```
